theme = "ron"

[palette]
black         = "#000000"
red           = "#cc9393"
green         = "#7f9f7f"
yellow        = "#f0dfaf"
blue          = "#6ca0a3"
magenta       = "#dc8cc3"
cyan          = "#93e0e3"
white         = "#dcdccc"
light_black   = "#666666"
light_red     = "#dca3a3"
light_green   = "#bfebbf"
light_yellow  = "#f0dfaf"
light_blue    = "#8cd0d3"
light_magenta = "#dc8cc3"
light_cyan    = "#93e0e3"
light_white   = "#ffffff"

"ui.background" = "black"
"ui.text"       = "white"
