[env]
TERM = "xterm-256color"
EDITOR = "vim"

[window]
opacity = 0.78
decorations = "None"
option_as_alt = "Both"
blur = false

[font]
size = 16.0
normal = { family = "DankMono Nerd Font Mono", style = "Regular" }

[window.padding]
x = 4
y = 4

[colors.primary]
background = '#000000'
foreground = '#bbc2cf'

[colors.cursor]
text = '#000000'
cursor = '#00FFFF'

