[window]
opacity = 0.8
decorations = "None"
option_as_alt = "Both"
blur = false

[font]
size = 14.0
normal = { family = "DankMono Nerd Font Mono", style = "Regular" }

[window.padding]
x = 4
y = 4

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#000000'
cursor = '#52afef'
