[window]
opacity = 0.8
decorations = "None"
dynamic_title = true
option_as_alt = "Both"
blur = false

[font]
size = 15.0
normal = { family = "DankMono Nerd Font Mono", style = "Regular" }

[window.padding]
x = 3
y = 3

[colors.primary]
background = '#000000'
